[features]
seeds = false
[programs.devnet]
solanacrowdfundingproject = "F7nnL8QeG9ELnu8CUJfQxtYaVEGTecd7ULrnV2ojxFCw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/aadyakalra/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
